### ISSUE TITLE
_interactDF.csv has malformatted output

### ISSUE THREAD

**Issue by DWgit** [Thakar-Lab/WikiNetworks#23]
Running the code below produces a mix of reasonable CSV and invalid output. Excerpt:

```
WP100,Glutathione metabolism,['e1568'],['Arrow'],#000000,[],,f7431,POINT (329 134),POINT (670 634),b31,670.0,634.0,POINT (329 134),b8ac0,329.0,134.0,0.0,b31,0.0,b8ac0,,,2.3.2.4,5-Oxoproline
WP100,Glutathione metabolism,"['c8453', 'e297a']",['Arrow'],#000000,[],,f840c,POINT (918 821),POINT (815 786),e5c,815.0,786.0,POINT (918 821),dca0d,918.0,821.0,0.0,e5c,0.0,dca0d,,,ANPEP,R-S-Alanine
WP100,Glutathione metabolism,,group,#nan,,b5967,c9b_f40_1,POINT (658 795.3333333333334),POINT (658 775.3333333333334),c9b,"31    658.0
Name: centerX, dtype: float64","31    775.333333
Name: centerY, dtype: float64",POINT (658 795.3333333333334),f40,"56    658.0
Name: centerX, dtype: float64","56    795.333333
Name: centerY, dtype: float64",0.0,c9b,0.0,f40,datanodeDF,datanodeDF,GGT1,GGTLA1
WP100,Glutathione metabolism,,group,#nan,,b5967,c9b_f40_2,POINT (658 775.3333333333334),POINT (658 795.3333333333334),f40,"56    658.0
```
The `Name:` rows are distinct lines in the CSV; it's not just bad formatting in this bug report.

The issue occurs with WikiNetworks Version: 1.1.2, running on conda Python 3.9.12

**Comment by DWgit** [comment]
```
from wikinetworks import *

pathwayID = 'WP100'

s = WikiPathways()
g = runParsePathway(s, pathwayID)
```

**Comment by muktapalshikar** [comment]
Thank you for this report. Essentially, the columns node1_x, node1_y, node2_x and node2_y were convenience columns containing the x and y coordinates as floats rather than the point objects already stored in the node1_coords and node2_coords columns. These values were being printed out in the csv as pandas series rather than individual floats. I didn't spot this error because it is actually a valid CSV since the values are quoted (for instance, Excel doesn't throw an error and accepts those values as part of a single cell). However, I've fixed this error in the wikipathways.py file on GitHub and have credited you in the pull request.

--
Mukta
